#!/usr/bin/env python3
"""Write tz-coords.js: IANA time zone -> [lat, lon] of the zone's principal city.

Usage:
    python3 scripts/build_tz_coords.py

theme.js looks up the visitor's time zone here to work out whether the sun is
up where they are.  The coordinates come from the system tz database
(/usr/share/zoneinfo): zone.tab and zone1970.tab, plus the old alias names in
tzdata.zi, which some browsers still report (e.g. Asia/Calcutta).  Whole
degrees are plenty: one degree moves sunrise by about four minutes, far less
than the spread of places that share a time zone.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZONEINFO = Path("/usr/share/zoneinfo")
OUT = ROOT / "tz-coords.js"


def degrees(sign: str, digits: str, deg_len: int) -> float:
    # ISO 6709 as used by zone.tab: ±DDMM[SS] / ±DDDMM[SS]
    d, m, s = int(digits[:deg_len]), int(digits[deg_len:deg_len + 2]), int(digits[deg_len + 2:] or 0)
    return (d + m / 60 + s / 3600) * (-1 if sign == "-" else 1)


def main() -> None:
    coords: dict[str, list[int]] = {}
    for tab in ("zone1970.tab", "zone.tab"):
        for line in (ZONEINFO / tab).read_text().splitlines():
            if line.startswith("#") or not line.strip():
                continue
            _, iso, zone = line.split("\t")[:3]
            m = re.fullmatch(r"([+-])(\d{4,6})([+-])(\d{5,7})", iso)
            coords.setdefault(zone, [round(degrees(m[1], m[2], 2)), round(degrees(m[3], m[4], 3))])

    # "L Asia/Kolkata Asia/Calcutta": the alias gets its target's coordinates
    for line in (ZONEINFO / "tzdata.zi").read_text().splitlines():
        if line.startswith("L "):
            _, target, alias = line.split()
            if target in coords:
                coords.setdefault(alias, coords[target])

    version = (ZONEINFO / "tzdata.zi").read_text().splitlines()[0].removeprefix("# version ").strip()
    body = json.dumps(dict(sorted(coords.items())), separators=(",", ":"))
    OUT.write_text(
        f"// Generated by scripts/build_tz_coords.py from tzdata {version}; do not edit by hand.\n"
        "// IANA time zone -> [latitude, longitude] of its principal city, whole degrees.\n"
        f"var TZ_COORDS = {body};\n"
    )
    print(f"{OUT.name}: {len(coords)} zones, {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
